# Generated by Django 6.0.4 on 2026-05-02 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userpayment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userpayment",
            options={"ordering": ["user", "-payment_date"], "verbose_name": "", "verbose_name_plural": ""},
        ),
        migrations.RenameField(
            model_name="userpayment",
            old_name="date_payment",
            new_name="payment_date",
        ),
    ]
