# Generated by Django 6.0.6 on 2026-07-12 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_userpayment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userpayment",
            options={
                "ordering": ["user", "-payment_date"],
                "verbose_name": "Оплата пользователя",
                "verbose_name_plural": "Оплаты пользователей",
            },
        ),
    ]
