FROM nginx:alpine

# Удаляем дефолтный конфиг
RUN rm /etc/nginx/conf.d/default.conf

# Копируем наш конфиг в правильное место
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# COPY html/ /usr/share/nginx/html/
# Создаем директории для статики (без копирования html)
RUN mkdir -p /usr/share/nginx/html/staticfiles && \
    mkdir -p /usr/share/nginx/html/media

# Устанавливаем права
RUN chown -R nginx:nginx /usr/share/nginx/html
