FROM nginx:latest

# Удаляем дефолтный конфиг
RUN rm /etc/nginx/conf.d/default.conf

# Копируем наш конфиг в правильное место
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

COPY html/ /usr/share/nginx/html/

