# Generated by Django 6.0.4 on 2026-04-30 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название курса", max_length=100, unique=True, verbose_name="Название курса"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        default="media/course_preview/default.jpg",
                        help_text="Загрузите превью курса",
                        null=True,
                        upload_to="media/course_preview",
                        verbose_name="Превью курса",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Введите описание курса", null=True, verbose_name="Описание курса"
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": ("Курсы",),
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название урока", max_length=100, verbose_name="Название урока"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Введите описание урока", null=True, verbose_name="Описание урока"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        default="media/lesson_preview/default.jpg",
                        help_text="Загрузите превью урока",
                        null=True,
                        upload_to="media/lesson_preview",
                        verbose_name="Превью урока",
                    ),
                ),
                (
                    "url_video",
                    models.URLField(
                        blank=True, help_text="Укажите ссылку на видео", null=True, verbose_name="Ссылка на видео"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Укажите курс урока",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course",
                        to="lms.course",
                        verbose_name="Курс урока",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": ("Уроки",),
                "ordering": ["title"],
            },
        ),
    ]
