# Generated by Django 6.0.4 on 2026-05-11 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_subscriptions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(
                blank=True, default=0, help_text="Укажите стоимость курса", null=True, verbose_name="Стоимость курса"
            ),
        ),
        migrations.CreateModel(
            name="CoursePayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.PositiveIntegerField(help_text="Укажите сумму оплаты", verbose_name="Сумма оплаты")),
                (
                    "session_id",
                    models.CharField(
                        blank=True, help_text="Укажите id сессии", max_length=255, null=True, verbose_name="Id сессии"
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Укажите ссылку на оплату",
                        max_length=400,
                        null=True,
                        verbose_name="Ссылка на оплату",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("open", "Оформление продолжается"),
                            ("expired", "Срок оформления истек"),
                            ("complete", "Оформление заверешено"),
                        ],
                        help_text="Укажите статус оплаты",
                        max_length=8,
                        null=True,
                        verbose_name="Статус оплаты",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите оплачиваемый курс",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="course_payment",
                        to="lms.course",
                        verbose_name="Оплачиваемый курс",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Укажите плательщика",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_course_payment",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Плательщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оплата курса",
                "verbose_name_plural": "Оплаты курсов",
                "ordering": ["course", "user"],
            },
        ),
    ]
