# Generated by Django 6.0.4 on 2026-05-12 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_course_price_сoursepayment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptions",
            name="user",
            field=models.ForeignKey(
                default=1,
                help_text="Пользователь",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subs_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
            preserve_default=False,
        ),
    ]
