# Generated by Django 6.0.4 on 2026-05-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_alter_subscriptions_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursepayment",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("open", "Оформление продолжается"),
                    ("expired", "Срок оформления истек"),
                    ("complete", "Оформление завершено"),
                ],
                help_text="Укажите статус оплаты",
                max_length=8,
                null=True,
                verbose_name="Статус оплаты",
            ),
        ),
    ]
