# Generated by Django 6.0.4 on 2026-05-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0006_alter_coursepayment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursepayment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на оплату курса",
                max_length=600,
                null=True,
                verbose_name="Ссылка на оплату курса",
            ),
        ),
        migrations.AlterField(
            model_name="coursepayment",
            name="session_id",
            field=models.CharField(
                blank=True, help_text="Укажите id сессии", max_length=500, null=True, verbose_name="Id сессии"
            ),
        ),
    ]
