name: Django CI/CD Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: lms
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpq-dev file

    - name: Install Poetry
      run: pipx install poetry

    - name: Configure Poetry
      run: |
        poetry config virtualenvs.in-project true

    - name: Install dependencies
      run: |
        poetry install --no-interaction --no-root

    - name: Cache Poetry dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Set environment variables
      run: |
        echo "SECRET_KEY=django-insecure-ci-test-key" >> $GITHUB_ENV
        echo "STRIPE_SECRET_KEY=sk_test_ci_dummy_key" >> $GITHUB_ENV
        echo "DB_NAME=lms" >> $GITHUB_ENV
        echo "DB_USER=postgres" >> $GITHUB_ENV
        echo "PASSWORD=postgres" >> $GITHUB_ENV
        echo "DB_HOST=localhost" >> $GITHUB_ENV
        echo "PORT=5432" >> $GITHUB_ENV
        echo "EMAIL_HOST_USER=test@example.com" >> $GITHUB_ENV
        echo "EMAIL_HOST_PASSWORD=test_password" >> $GITHUB_ENV
        echo "CELERY_BROKER_URL=redis://localhost:6379/0" >> $GITHUB_ENV
        echo "CELERY_RESULT_BACKEND=redis://localhost:6379/0" >> $GITHUB_ENV
        echo "REDIS_HOST=localhost" >> $GITHUB_ENV
        echo "GITHUB_ACTIONS=true" >> $GITHUB_ENV

    - name: Debug environment
      run: |
        echo "DB_NAME=$DB_NAME"
        echo "DB_USER=$DB_USER"
        echo "DB_HOST=$DB_HOST"

    - name: Set Python path
      run: |
        echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

    - name: Run migrations
      run: |
        export PYTHONPATH=$PWD
        poetry run python manage.py migrate

    - name: Run tests
      run: |
        export PYTHONPATH=$PWD
        poetry run python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.10.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Add server to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts


    - name: Copy project files to server
      run: |
        rsync -avz --rsync-path="sudo rsync" --exclude '__pycache__' . ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.DEPLOY_DIR }}

    - name: Deploy application
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd ${{ secrets.DEPLOY_DIR }}
          sudo chown -R $USER:$USER .
          sudo chmod -R 755 .
          rm -rf venv
          python3.14 -m venv venv
          source venv/bin/activate
          python3.14 -m pip install --upgrade pip
          pip install psycopg2-binary
          pip install -r requirements.txt
          pip install django
          pip install celery
          pip install dotenv
          pip install djangorestframework
          pip install drf-spectacular
          pip install drf-yasg
          pip install django-cors-headers
          pip install django-filter
          python manage.py migrate
          python manage.py collectstatic --noinput
          sudo systemctl restart myapp.service
        EOF

